PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix ad: <http://examplesparql.com/n/actordata#>
prefix md: <http://examplesparql.com/n/moviedata#>
prefix d: <http://examplesparql.com/n/data#>

SELECT ?movie ?year
WHERE {
  ?Movie md:moviename ?movie;
               md:year ?year.
}